server:
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    path: /error
  port: 9010
#  address: 192.168.1.254
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/org_meta?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1290
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: soportemetacontrol@gmail.com
    password: mublcdprtqvcndhl
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  report:
      mail: "diego.cortes@metacontrol.cl"
      mailjefe: "diego.cortes@metacontrol.cl"
      ejecucion: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
